{"name": "Логин с неверным логином и паролем", "status": "passed", "start": 1721746432706, "stop": 1721746432904, "uuid": "609bef4e-c5b6-40d9-85d6-27189e2f1531", "historyId": "73a3c4a58454bd2f8fda895af19e9600", "testCaseId": "73a3c4a58454bd2f8fda895af19e9600", "fullName": "tests.test_login_user.TestLoginUser#test_unsuccess_login", "labels": [{"name": "suite", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-5FK58OB"}, {"name": "thread", "value": "9476-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}