{"name": "Логин с неверным логином и паролем", "status": "passed", "start": 1721746362874, "stop": 1721746363141, "uuid": "27329609-e078-4ce3-bd80-f94a05ff10dd", "historyId": "73a3c4a58454bd2f8fda895af19e9600", "testCaseId": "73a3c4a58454bd2f8fda895af19e9600", "fullName": "tests.test_login_user.TestLoginUser#test_unsuccess_login", "labels": [{"name": "suite", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-5FK58OB"}, {"name": "thread", "value": "1524-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}