{"name": "Получение номера заказа зарегистрированного пользователя", "status": "broken", "statusDetails": {"message": "KeyError: 'accessToken'", "trace": "@pytest.fixture(scope=\"function\")\n    def create_user():\n        payload = User.register_new_user()\n        login_data = payload.copy()\n        del login_data[\"name\"]\n        double_email = payload.copy()\n        del double_email[\"name\"]\n        del double_email[\"password\"]\n        response = requests.post(configuration.CREATE_USER_PATH, data=payload)\n>       token = response.json()[\"accessToken\"]\nE       KeyError: 'accessToken'\n\nconftest.py:16: KeyError"}, "start": 1721746413685, "stop": 1721746413685, "uuid": "97a38893-0c9f-4282-9a37-57b86dcfcf91", "historyId": "b6f2fcf86e7b3d9e70627392ad575135", "testCaseId": "b6f2fcf86e7b3d9e70627392ad575135", "fullName": "tests.test_get_user_order.TestGetUserOrder#test_get_user_order_auth", "labels": [{"name": "suite", "value": "Получение заказов конкретного пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestGetUserOrder"}, {"name": "host", "value": "DESKTOP-5FK58OB"}, {"name": "thread", "value": "12140-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_get_user_order"}]}