{"name": "Логин с неверным логином и паролем", "status": "passed", "start": 1721746393882, "stop": 1721746394109, "uuid": "732b0b2e-b85d-4f5f-934e-acc8bac73a34", "historyId": "73a3c4a58454bd2f8fda895af19e9600", "testCaseId": "73a3c4a58454bd2f8fda895af19e9600", "fullName": "tests.test_login_user.TestLoginUser#test_unsuccess_login", "labels": [{"name": "suite", "value": "Авторизация пользователя"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestLoginUser"}, {"name": "host", "value": "DESKTOP-5FK58OB"}, {"name": "thread", "value": "8076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_user"}]}